const DAY_ENERGY_COST = 0.2
const NIGHT_ENERGY_COST = 0.1
const SOLD_ENERGY_GAIN = 0.1
const FOOD_PRICE = 10
const BAD_WEATHER_PROB = 0.02
const DIRT_CHANCE = 0.1

module.exports = {DAY_ENERGY_COST, NIGHT_ENERGY_COST, SOLD_ENERGY_GAIN, FOOD_PRICE, BAD_WEATHER_PROB, DIRT_CHANCE}